import { spawn } from "node:child_process";
import { mkdir, readdir, stat, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import { h } from "preact";
import { render } from "preact-render-to-string";

const __dirname = path.dirname(fileURLToPath(import.meta.url));

const srcDir = path.join(__dirname, "src");
const pagesDir = path.join(srcDir, "pages");
const publicDir = path.join(__dirname, "public");
const isWatchMode = process.argv.includes("--watch");

const pages = [
  {
    entry: "index.jsx",
    output: "index.html",
  },
  {
    entry: "legal.jsx",
    output: "legal.html",
  },
  {
    entry: "support.jsx",
    output: "support.html",
  },
  {
    entry: "ejemplos.jsx",
    output: "ejemplos.html",
  },
];

async function importPageComponent(entryPath) {
  const moduleUrl = pathToFileURL(entryPath);
  moduleUrl.searchParams.set("t", `${Date.now()}`);
  const pageModule = await import(moduleUrl.href);

  if (typeof pageModule.default !== "function") {
    throw new Error(
      `Page module ${path.relative(__dirname, entryPath)} must export a default component`,
    );
  }

  return pageModule.default;
}

async function build() {
  await mkdir(publicDir, { recursive: true });

  for (const page of pages) {
    const entryPath = path.join(pagesDir, page.entry);
    const outputPath = path.join(publicDir, page.output);
    const Page = await importPageComponent(entryPath);
    const html = render(h(Page), {}, { pretty: "  " });
    const generated = [
      "<!doctype html>",
      "<!-- Generated by `npm run build`. Edit `src/pages` and `src/components`. -->",
      html,
    ].join("\n");

    await writeFile(outputPath, generated, "utf8");
  }
}

async function runBuildInSubprocess() {
  return await new Promise((resolve) => {
    const child = spawn(
      process.execPath,
      ["--import", "tsx", path.join(__dirname, "build.mjs")],
      {
        cwd: __dirname,
        stdio: "inherit",
      },
    );

    child.on("close", (code) => {
      resolve(code === 0);
    });

    child.on("error", (error) => {
      console.error(`[build:web] ${error.message}`);
      resolve(false);
    });
  });
}

async function runBuild() {
  try {
    if (isWatchMode) {
      return await runBuildInSubprocess();
    }

    await build();
    console.log("[build:web] updated html pages");
    return true;
  } catch (error) {
    console.error(`[build:web] ${error.message}`);
    return false;
  }
}

function startWatchMode() {
  const pollIntervalMs = 300;
  let previousSnapshot = "";
  let checking = false;

  const readSnapshot = async () => {
    const files = await collectSourceFiles(srcDir);

    files.sort();

    const parts = await Promise.all(
      files.map(async (file) => {
        const info = await stat(file);
        return `${path.relative(__dirname, file)}:${info.size}:${info.mtimeMs}`;
      }),
    );

    return parts.join("|");
  };

  const interval = setInterval(async () => {
    if (checking) return;
    checking = true;

    try {
      const nextSnapshot = await readSnapshot();

      if (nextSnapshot !== previousSnapshot) {
        previousSnapshot = nextSnapshot;
        await runBuild();
      }
    } catch (error) {
      console.error(`[build:web] ${error.message}`);
    } finally {
      checking = false;
    }
  }, pollIntervalMs);

  const stopWatching = () => {
    clearInterval(interval);
    process.exit(0);
  };

  process.on("SIGINT", stopWatching);
  process.on("SIGTERM", stopWatching);

  readSnapshot()
    .then((snapshot) => {
      previousSnapshot = snapshot;
    })
    .catch((error) => {
      console.error(`[build:web] ${error.message}`);
    });

  console.log(`[build:web] watching src/ (${pollIntervalMs}ms polling)`);
}

async function collectSourceFiles(dir) {
  const entries = await readdir(dir, { withFileTypes: true });
  const files = [];

  for (const entry of entries) {
    const fullPath = path.join(dir, entry.name);

    if (entry.isDirectory()) {
      files.push(...(await collectSourceFiles(fullPath)));
      continue;
    }

    if (!entry.isFile()) continue;
    if (!/\.(jsx|js|mjs)$/.test(entry.name)) continue;
    files.push(fullPath);
  }

  return files;
}

async function main() {
  const ok = await runBuild();

  if (!isWatchMode) {
    process.exitCode = ok ? 0 : 1;
    return;
  }

  startWatchMode();
}

main().catch((error) => {
  console.error(`[build:web] ${error.message}`);
  process.exitCode = 1;
});
